<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<title>
    {{ filled($title ?? null) ? $title.' - '.config('app.name', 'Laravel') : config('app.name', 'Laravel') }}
</title>

<link rel="icon" href="/favicon.ico" sizes="any">
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="apple-touch-icon" href="/apple-touch-icon.png">

<link rel="preconnect" href="https://fonts.bunny.net">
<link href="https://fonts.bunny.net/css?family=instrument-sans:400,500,600" rel="stylesheet" />
<link rel="stylesheet" href="{{ asset('css/iziToast.css') }}" />
<link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css" />
<script src="https://code.jquery.com/jquery-3.7.1.min.js" ></script>
<script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.min.js"></script>

@vite(['resources/css/app.css', 'resources/js/app.js'])

{{--
    Bridge for utility classes used by the newer admin screens that are not in
    the compiled stylesheet.

    public/build is generated by `npm run build`; a Tailwind class that was not
    already used somewhere in the app when that last ran resolves to no rule at
    all. This keeps those screens looking right in the meantime. Delete this
    block once the assets are rebuilt -- Tailwind will emit all of it properly.

    Requires Node 20+ (package.json pins Vite 8); the Node bundled with Laragon
    is 18 and cannot run the build.
--}}
<style id="utility-bridge">
    .bg-sky-50{background-color:#f0f9ff}
    .bg-sky-700{background-color:#0369a1}
    .bg-slate-50{background-color:#f8fafc}
    .bg-slate-200{background-color:#e2e8f0}
    .bg-slate-900\/40{background-color:rgba(15,23,42,.4)}
    .border-sky-200{border-color:#bae6fd}
    .border-slate-100{border-color:#f1f5f9}
    .text-amber-900{color:#78350f}
    .text-sky-700{color:#0369a1}
    .text-sky-900{color:#0c4a6e}
    .text-slate-300{color:#cbd5e1}
    .text-slate-400{color:#94a3b8}
    .text-slate-800{color:#1e293b}
    .disabled\:opacity-50:disabled{opacity:.5}
    .disabled\:opacity-60:disabled{opacity:.6}
    :where(.dark) .bg-sky-950\/40{background-color:rgba(8,47,73,.4)}
    :where(.dark) .border-sky-900{border-color:#0c4a6e}
    :where(.dark) .text-sky-200{color:#bae6fd}
    :where(.dark) .text-zinc-200{color:#e4e4e7}

    /* Layout. These matter more than the colours above: without them a
       multi-column dashboard collapses into one column with no spacing. */
    .space-y-1>:not([hidden])~:not([hidden]){margin-top:.25rem}
    .space-y-2>:not([hidden])~:not([hidden]){margin-top:.5rem}
    .space-y-3>:not([hidden])~:not([hidden]){margin-top:.75rem}
    .space-y-4>:not([hidden])~:not([hidden]){margin-top:1rem}
    .space-y-5>:not([hidden])~:not([hidden]){margin-top:1.25rem}
    .space-y-6>:not([hidden])~:not([hidden]){margin-top:1.5rem}
    .gap-x-2{column-gap:.5rem}
    .gap-y-1{row-gap:.25rem}

    @media (min-width:640px){
        .sm\:grid-cols-2{grid-template-columns:repeat(2,minmax(0,1fr))}
        .sm\:grid-cols-3{grid-template-columns:repeat(3,minmax(0,1fr))}
        .sm\:col-span-2{grid-column:span 2/span 2}
    }
    @media (min-width:1024px){
        .lg\:grid-cols-2{grid-template-columns:repeat(2,minmax(0,1fr))}
        .lg\:grid-cols-3{grid-template-columns:repeat(3,minmax(0,1fr))}
    }
    @media (min-width:1280px){
        .xl\:grid-cols-2{grid-template-columns:repeat(2,minmax(0,1fr))}
        .xl\:grid-cols-3{grid-template-columns:repeat(3,minmax(0,1fr))}
        .xl\:grid-cols-4{grid-template-columns:repeat(4,minmax(0,1fr))}
    }
</style>
<script src="{{ asset('js/iziToast.js') }}"></script>
@fluxAppearance
<script>
    // Default to light mode when no explicit appearance has been chosen.
    window.Flux.applyAppearance(window.localStorage.getItem('flux.appearance') || 'light')
</script>
